### ISSUE TITLE
Datetime.jl is deprecated

### ISSUE THREAD

**Issue by vikjam** [farrellm/YTables.jl#2]
I got a warning that Datetime.jl is being replaced by Dates.jl. Not sure if it matters much because I didn't really see where dates were being used in the code of YTables.jl, but I thought it would be worth updating!

```
WARNING: The Datetime.jl package is deprecated, but will remain maintained for the 0.3 release.
Please consider using the Dates.jl package instead, which mirrors the Dates module in Base Julia in 0.4
```

**Comment by farrellm** [comment]
YTables.jl no longer depends on Datetime.jl, and now supports Julia 0.5!
